version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - springboot-microservices-network
  keycloak:
    image: docker.io/bitnami/keycloak:latest
    hostname: keycloak
    ports:
      - "8091:8091"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_HTTP_PORT=8091
      - KEYCLOAK_EXTRA_ARGS=--import-realm
    depends_on:
      - postgresql
    volumes:
      - './realms:/opt/bitnami/keycloak/data/import'
    networks:
      - springboot-microservices-network
  springboot-microservice:
    image: springboot-microservice:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /data/springboot-microservice
    ports:
      - "8080:8080"
    depends_on:
      - keycloak
    networks:
      - springboot-microservices-network
volumes:
  postgresql_data:
    driver: local
networks:
    springboot-microservices-network:
        driver: bridge
